version: 1
update_configs:
  - package-manager: 'javascript'
    directory: '/''
    update_schedule: 'daily'
    target_branch: 'main'
    allowed_updates:
      - match:
          dependency_type: 'all'
          update_type: 'all'
      version_requirement_updates: 'off'
